name: Update Joke

on:
  workflow_dispatch:  #Manually trigger the workflow
  schedule:
    - cron: '0 7 * * *'  # Schedule daily at 12:01 AM Indian Time

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Update Joke
        run: node update-joke.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit the changes
        run: |
          git config --global user.name "IsaacLiraa"
          git config --global user.email "instancememo@gmail.com"
          git add README.md
          git commit -m "Update daily joke"
          git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/IsaacLiraa/IsaacLiraa.git
