name: Daily Joke Update

on:
  schedule:
    - cron: '0 7 * * *'  # Runs every day at 7:00 AM UTC
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  update-joke:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies (if any, in this case, none are needed)
      - name: Install dependencies
        run: npm install

      # Run the update joke script
      - name: Run update-joke.js
        run: node update-joke.js

      # Commit and push the updated README.md
      - name: Commit and push changes
        run: |
          git config --global user.name "IsaacLiraa"
          git config --global user.email "instancememo@gmail.com"
          git add README.md
          git commit -m "Update daily joke"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.DJ_TOKEN }}
