name: Daily Joke Update

on:
  schedule:
    - cron: '0 7 * * *'  # This runs the workflow every day at 7:00 AM UTC (4:00 AM Atlantic Time)
  workflow_dispatch:  # This allows you to manually trigger the workflow from the Actions tab

jobs:
  update-joke:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Removed npm install step as it's not necessary
    # No external dependencies are used in the update-joke.js script
    
    - name: Run the update joke script
      run: node update-joke.js

    - name: Commit the changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add README.md
        git commit -m "Update daily joke"
        git push
