name: Daily Joke
run-name: ${{ github.actor }} is Updating The Joke
on: [push]
jobs:
  update-joke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: node update-joke.js
      - run: |
          git config --global user.name "IsaacLiraa"
          git config --global user.email instancememo@gmail.com"
          git add README.md
          git commit -m "Update daily joke"
          git push
